name: CI
on: 
  workflow_dispatch:
  schedule:
  - cron:  '0 0 * * *'
jobs:
  composer:
    runs-on: ubuntu-latest
    steps:
      - name: Get current date
        id: version
        run: |
          echo "builddate=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT
      - uses: actions/checkout@v1
      - uses: nanasess/setup-php@master
        with:
          php-version: '8.2'

      - run: php ./run.php ${{ secrets.GOOGLE_TOKEN }}
        env:
          GOOGLE_TOKEN: ${{secrets.GOOGLE_TOKEN}}

      - run: git config --global user.email "support@svlstudios.com" && git config --global user.name "SVL Studios"
      - run: git add -f -A
      - run: git commit -m "Google Fonts Update: ${{ steps.version.outputs.builddate }} (Build $GITHUB_RUN_NUMBER)"
      - run: git push "https://x-access-token:$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY" HEAD:master
      
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
