name: CI
on: 
  workflow_dispatch:
  schedule:
  - cron:  '0 0 * * *'
jobs:
  composer:
    runs-on: ubuntu-latest
    steps:
      - name: Get current date
        id: date
        run: echo " ::set-output name=date::$(date +'%Y-%m-%d')"
      - uses: actions/checkout@v1
      - uses: nanasess/setup-php@master
        with:
          php-version: '7.4'
          
      - run: git config --global user.email "support@svlstudios.com" && git config --global user.name "SVL Studios"
      - run: git rm -f google_fonts.json
      - run: git commit -a -m "Delete"
      - run: git push "https://x-access-token:$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY" HEAD:master
      
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
